name: dialog
channels:
  - conda-forge
dependencies:
  - python=3.5
  - jupyter
  - pandas
  - numpy
  - pip:
      - tensorflow==2.0.0-alpha0
      - nltk==3.4.5
      - pytest==5.2.0
      - spacy==2.1.8
